Repository Persinus/App_Learn_KOREAN_EXPO_ReactNative, pull requests merged in 2025-05, with the labels that each got.

#11 Create dependabot.yml
  .github/dependabot.yml
Labels: size/S

#22 Thêm thông tin chi tiết cho ứng dụng và phân tích back-end
  Front-App/DetailApp.txt
Labels: size/L

#23 thêm các trường cần code backend
  Front-App/App.js
Labels: size/XS

#29 Implement modularized API routes, schemas, and enhanced configuration for the application
  Back-End/.env
  Back-End/Schema/AchievementsSchema.js
  Back-End/Schema/DailymissionSchema.js
  Back-End/Schema/VocabularySchema.js
  Back-End/Schema/lessonSchema.js
  Back-End/Schema/loginSchema.js
  Back-End/Schema/notificationSchema.js
  Back-End/Schema/registerSchema.js
  Back-End/routes/Achivement.js
  Back-End/routes/DailyMission.js
  Back-End/routes/Lesson.js
  Back-End/routes/Nofication.js
  Back-End/routes/User.js
  Back-End/routes/Users.js
  Back-End/routes/Vocabulary.js
  Back-End/routes/auth.js
  Back-End/server.js
  Front-App/DetailApp.txt
  Front-App/Store/Authorization.js
  Front-App/Store/Store.js
  Front-App/utils/axios.js
Labels: size/XL

#30 chú ý
  Front-App/DetailApp.txt
Labels: size/XS

#48 Build dùm Thọ
  Front-App/assets/Lession1.jpg
  Front-App/assets/Lession2.jpg
  Front-App/assets/Lession3.jpg
  Front-App/assets/avatar_1.jpg
  Front-App/assets/avatar_2.jpg
  Front-App/assets/avatar_3.jpg
  Front-App/assets/avatar_4.jpg
  Front-App/assets/background.jpg
  Front-App/assets/illustration1.jpg
  Front-App/assets/illustration2.jpg
  Front-App/assets/logo.jpg
  Front-App/assets/rank_a.jpg
  Front-App/assets/rank_b.jpg
  Front-App/assets/rank_c.jpg
  Front-App/assets/rank_s.jpg
Labels: size/XS

#56 Fix app lần cuối trước khi build
  Navigation/AppNavigator.js
  Navigation/FriendStack.js
  Navigation/HomeStack.js
  Navigation/SettingStack.js
  Screens/Auth/LoginPage.js
  Screens/Auth/LoginScreen.js
  Screens/ComingSoon.js
  Screens/Friend/ChatRealtime.js
  Screens/Friend/FriendScreen.js
  Screens/Friend/UserDetail.js
  Screens/Home/Achievement.js
  Screens/Home/DailyMission.js
  Screens/Home/DailyReward.js
  Screens/Home/HomeScreen.js
  Screens/Home/allAchievement.js
  Screens/Home/allDailyMission.js
  Screens/KoreanBasics/BasicKoreanLessonsScreen.js
  Screens/KoreanBasics/LessonDetailScreen.js
  Screens/Notifications/NotificationsScreen.js
  Screens/PaidCourses/JoinCourse.js
  Screens/PaidCourses/LinkingPaid.js
  Screens/PaidCourses/PaidCoursesDetail.js
  Screens/PaidCourses/PaidCoursesScreen.js
  Screens/Practice/Game/MiniGame1.js
  Screens/Practice/Game/MiniGame2.js
  Screens/Practice/PracticeScreen.js
  Screens/Practice/Rewards/PracticeAchievements.js
  Screens/Practice/Rewards/PracticeDailyReward.js
  Screens/Practice/Rewards/PracticeLevelUp.js
  Screens/Practice/VideoDetailScreen.js
  Screens/Practice/VideoListScreen.js
  Screens/Rankings/RankingsScreen.js
  Screens/Setting/ChangePasswordScreen.js
  Screens/Setting/EditInfoUser.js
  Screens/Setting/InfoApp.js
  Screens/Setting/SettingsScreen.js
  Screens/Setting/UserFeedback.js
  app.json
  assets/Card.json
  assets/Lession3.png
  assets/avatar_1.jpg
  assets/avatar_2.jpg
  assets/avatar_3.jpg
  assets/avatar_4.jpg
  assets/background.jpg
  assets/icon.png
  assets/logo.jpg
  assets/logo.png
  assets/rank_a.jpg
  assets/rank_b.jpg
  assets/rank_c.jpg
  assets/rank_s.jpg
  utils/NotificationHelper.js
  utils/axios.js
Labels: size/XXL

#57 Nguyen manh
  app.json
Labels: size/XS
